import {
  AArrowDown,
  AArrowUp,
  ALargeSmall,
  Accessibility,
  Activity,
  AirVent,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmSmoke,
  Album,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  AlignVerticalDistributeEnd,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Ambulance,
  Ampersand,
  Ampersands,
  Amphora,
  Anchor,
  Angry,
  Annoyed,
  Antenna,
  Anvil,
  Aperture,
  AppWindow,
  AppWindowMac,
  Apple,
  Archive,
  ArchiveRestore,
  ArchiveX,
  Armchair,
  ArrowBigDown,
  ArrowBigDownDash,
  ArrowBigLeft,
  ArrowBigLeftDash,
  ArrowBigRight,
  ArrowBigRightDash,
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDown01,
  ArrowDown10,
  ArrowDownAZ,
  ArrowDownFromLine,
  ArrowDownLeft,
  ArrowDownNarrowWide,
  ArrowDownRight,
  ArrowDownToDot,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowDownZA,
  ArrowLeft,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightFromLine,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUp01,
  ArrowUp10,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpFromLine,
  ArrowUpLeft,
  ArrowUpNarrowWide,
  ArrowUpRight,
  ArrowUpToLine,
  ArrowUpWideNarrow,
  ArrowUpZA,
  ArrowsUpFromLine,
  Asterisk,
  AtSign,
  Atom,
  AudioLines,
  AudioWaveform,
  Award,
  Axe,
  Axis3d,
  Baby,
  Backpack,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeIndianRupee,
  BadgeInfo,
  BadgeJapaneseYen,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgePoundSterling,
  BadgeQuestionMark,
  BadgeRussianRuble,
  BadgeSwissFranc,
  BadgeX,
  BaggageClaim,
  Ban,
  Banana,
  Bandage,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BanknoteX,
  Barcode,
  Barrel,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryWarning,
  Beaker,
  Bean,
  BeanOff,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BellDot,
  BellElectric,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  BicepsFlexed,
  Bike,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Bitcoin,
  Blend,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bolt,
  Bomb,
  Bone,
  Book,
  BookA,
  BookAlert,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  BoomBox,
  Bot,
  BotMessageSquare,
  BotOff,
  BottleWine,
  BowArrow,
  Box,
  Boxes,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  BrickWall,
  BrickWallFire,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseConveyorBelt,
  BriefcaseMedical,
  BringToFront,
  Brush,
  BrushCleaning,
  Bubbles,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Building2,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  Calendar1,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarMinus2,
  CalendarOff,
  CalendarPlus,
  CalendarPlus2,
  CalendarRange,
  CalendarSearch,
  CalendarSync,
  CalendarX,
  CalendarX2,
  Camera,
  CameraOff,
  Candy,
  CandyCane,
  CandyOff,
  Cannabis,
  Captions,
  CaptionsOff,
  Car,
  CarFront,
  CarTaxiFront,
  Caravan,
  CardSim,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  Cctv,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  Check,
  CheckCheck,
  CheckLine,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsLeftRight,
  ChevronsLeftRightEllipsis,
  ChevronsRight,
  ChevronsRightLeft,
  ChevronsUp,
  ChevronsUpDown,
  Chrome,
  Church,
  Cigarette,
  CigaretteOff,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowOutDownLeft,
  CircleArrowOutDownRight,
  CircleArrowOutUpLeft,
  CircleArrowOutUpRight,
  CircleArrowRight,
  CircleArrowUp,
  CircleCheck,
  CircleCheckBig,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDashed,
  CircleDivide,
  CircleDollarSign,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CircleEqual,
  CircleFadingArrowUp,
  CircleFadingPlus,
  CircleGauge,
  CircleMinus,
  CircleOff,
  CircleParking,
  CircleParkingOff,
  CirclePause,
  CirclePercent,
  CirclePlay,
  CirclePlus,
  CirclePoundSterling,
  CirclePower,
  CircleQuestionMark,
  CircleSlash,
  CircleSlash2,
  CircleSmall,
  CircleStop,
  CircleUser,
  CircleUserRound,
  CircleX,
  CircuitBoard,
  Citrus,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardMinus,
  ClipboardPaste,
  ClipboardPen,
  ClipboardPenLine,
  ClipboardPlus,
  ClipboardType,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  ClockAlert,
  ClockArrowDown,
  ClockArrowUp,
  ClockFading,
  ClockPlus,
  Cloud,
  CloudAlert,
  CloudCheck,
  CloudCog,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  CloudUpload,
  Cloudy,
  Clover,
  Club,
  Code,
  CodeXml,
  Codepen,
  Codesandbox,
  Coffee,
  Cog,
  Coins,
  Columns2,
  Columns3,
  Columns3Cog,
  Columns4,
  Combine,
  Command,
  Compass,
  Component,
  Computer,
  ConciergeBell,
  Cone,
  Construction,
  Contact,
  ContactRound,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  Copy,
  CopyCheck,
  CopyMinus,
  CopyPlus,
  CopySlash,
  CopyX,
  Copyleft,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreativeCommons,
  CreditCard,
  Croissant,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Currency,
  Cylinder,
  Dam,
  Database,
  DatabaseBackup,
  DatabaseZap,
  DecimalsArrowLeft,
  DecimalsArrowRight,
  Delete,
  Dessert,
  Diameter,
  Diamond,
  DiamondMinus,
  DiamondPercent,
  DiamondPlus,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Diff,
  Disc,
  Disc2,
  Disc3,
  DiscAlbum,
  Divide,
  Dna,
  DnaOff,
  Dock,
  Dog,
  DollarSign,
  Donut,
  DoorClosed,
  DoorClosedLocked,
  DoorOpen,
  Dot,
  Download,
  DraftingCompass,
  Drama,
  Dribbble,
  Drill,
  Drone,
  Droplet,
  DropletOff,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  EarOff,
  Earth,
  EarthLock,
  Eclipse,
  Egg,
  EggFried,
  EggOff,
  Ellipsis,
  EllipsisVertical,
  Equal,
  EqualApproximately,
  EqualNot,
  Eraser,
  EthernetPort,
  Euro,
  Expand,
  ExternalLink,
  Eye,
  EyeClosed,
  EyeOff,
  Facebook,
  Factory,
  Fan,
  FastForward,
  Feather,
  Fence,
  FerrisWheel,
  Figma,
  File,
  FileArchive,
  FileAudio,
  FileAudio2,
  FileAxis3d,
  FileBadge,
  FileBadge2,
  FileBox,
  FileChartColumn,
  FileChartColumnIncreasing,
  FileChartLine,
  FileChartPie,
  FileCheck,
  FileCheck2,
  FileClock,
  FileCode,
  FileCode2,
  FileCog,
  FileDiff,
  FileDigit,
  FileDown,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileJson2,
  FileKey,
  FileKey2,
  FileLock,
  FileLock2,
  FileMinus,
  FileMinus2,
  FileMusic,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePlus,
  FilePlus2,
  FileQuestionMark,
  FileScan,
  FileSearch,
  FileSearch2,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileUser,
  FileVideo,
  FileVideo2,
  FileVolume,
  FileVolume2,
  FileWarning,
  FileX,
  FileX2,
  Files,
  Film,
  Fingerprint,
  FireExtinguisher,
  Fish,
  FishOff,
  FishSymbol,
  Flag,
  FlagOff,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  Flashlight,
  FlashlightOff,
  FlaskConical,
  FlaskConicalOff,
  FlaskRound,
  FlipHorizontal,
  FlipHorizontal2,
  FlipVertical,
  FlipVertical2,
  Flower,
  Flower2,
  Focus,
  FoldHorizontal,
  FoldVertical,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Folders,
  Footprints,
  Forklift,
  Forward,
  Frame,
  Framer,
  Frown,
  Fuel,
  Fullscreen,
  Funnel,
  FunnelPlus,
  FunnelX,
  GalleryHorizontal,
  GalleryHorizontalEnd,
  GalleryThumbnails,
  GalleryVertical,
  GalleryVerticalEnd,
  Gamepad,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  GeorgianLari,
  Ghost,
  Gift,
  GitBranch,
  GitBranchPlus,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitGraph,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  GitPullRequestClosed,
  GitPullRequestCreate,
  GitPullRequestCreateArrow,
  GitPullRequestDraft,
  Github,
  Gitlab,
  GlassWater,
  Glasses,
  Globe,
  GlobeLock,
  Goal,
  Gpu,
  Grab,
  GraduationCap,
  Grape,
  Grid2x2,
  Grid2x2Check,
  Grid2x2Plus,
  Grid2x2X,
  Grid3x2,
  Grid3x3,
  Grip,
  GripHorizontal,
  GripVertical,
  Group,
  Guitar,
  Ham,
  Hamburger,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HardHat,
  Hash,
  Haze,
  HdmiPort,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  HeadphoneOff,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartMinus,
  HeartOff,
  HeartPlus,
  HeartPulse,
  Heater,
  Hexagon,
  Highlighter,
  History,
  Hop,
  HopOff,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HousePlug,
  HousePlus,
  HouseWifi,
  IceCreamBowl,
  IceCreamCone,
  IdCard,
  IdCardLanyard,
  Image,
  ImageDown,
  ImageMinus,
  ImageOff,
  ImagePlay,
  ImagePlus,
  ImageUp,
  ImageUpscale,
  Images,
  Import,
  Inbox,
  IndentDecrease,
  IndentIncrease,
  IndianRupee,
  Infinity,
  Info,
  InspectionPanel,
  Instagram,
  Italic,
  IterationCcw,
  IterationCw,
  JapaneseYen,
  Joystick,
  Kanban,
  Key,
  KeyRound,
  KeySquare,
  Keyboard,
  KeyboardMusic,
  KeyboardOff,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  LaptopMinimal,
  LaptopMinimalCheck,
  Lasso,
  LassoSelect,
  Laugh,
  Layers,
  Layers2,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Leaf,
  LeafyGreen,
  Lectern,
  LetterText,
  Library,
  LibraryBig,
  LifeBuoy,
  Ligature,
  Lightbulb,
  LightbulbOff,
  LineSquiggle,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListCheck,
  ListChecks,
  ListCollapse,
  ListEnd,
  ListFilter,
  ListFilterPlus,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListStart,
  ListTodo,
  ListTree,
  ListVideo,
  ListX,
  Loader,
  LoaderCircle,
  LoaderPinwheel,
  Locate,
  LocateFixed,
  LocateOff,
  LocationEdit,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  LogIn,
  LogOut,
  Logs,
  Lollipop,
  Luggage,
  Magnet,
  Mail,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestionMark,
  MailSearch,
  MailWarning,
  MailX,
  Mailbox,
  Mails,
  Map,
  MapPin,
  MapPinCheck,
  MapPinCheckInside,
  MapPinHouse,
  MapPinMinus,
  MapPinMinusInside,
  MapPinOff,
  MapPinPlus,
  MapPinPlusInside,
  MapPinX,
  MapPinXInside,
  MapPinned,
  MapPlus,
  Mars,
  MarsStroke,
  Martini,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  MegaphoneOff,
  Meh,
  MemoryStick,
  Menu,
  Merge,
  MessageCircle,
  MessageCircleCode,
  MessageCircleDashed,
  MessageCircleHeart,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageCircleQuestionMark,
  MessageCircleReply,
  MessageCircleWarning,
  MessageCircleX,
  MessageSquare,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquareDiff,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareLock,
  MessageSquareMore,
  MessageSquareOff,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MessageSquareShare,
  MessageSquareText,
  MessageSquareWarning,
  MessageSquareX,
  MessagesSquare,
  Mic,
  MicOff,
  MicVocal,
  Microchip,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  MilkOff,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  MonitorCheck,
  MonitorCog,
  MonitorDot,
  MonitorDown,
  MonitorOff,
  MonitorPause,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorStop,
  MonitorUp,
  MonitorX,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Mouse,
  MouseOff,
  MousePointer,
  MousePointer2,
  MousePointerBan,
  MousePointerClick,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveDown,
  MoveDownLeft,
  MoveDownRight,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveUpLeft,
  MoveUpRight,
  MoveVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Navigation2Off,
  NavigationOff,
  Network,
  Newspaper,
  Nfc,
  NonBinary,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  NotepadTextDashed,
  Nut,
  NutOff,
  Octagon,
  OctagonAlert,
  OctagonMinus,
  OctagonPause,
  OctagonX,
  Omega,
  Option,
  Orbit,
  Origami,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PaintbrushVertical,
  Palette,
  Panda,
  PanelBottom,
  PanelBottomClose,
  PanelBottomDashed,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftDashed,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightDashed,
  PanelRightOpen,
  PanelTop,
  PanelTopClose,
  PanelTopDashed,
  PanelTopOpen,
  PanelsLeftBottom,
  PanelsRightBottom,
  PanelsTopLeft,
  Paperclip,
  Parentheses,
  ParkingMeter,
  PartyPopper,
  Pause,
  PawPrint,
  PcCase,
  Pen,
  PenLine,
  PenOff,
  PenTool,
  Pencil,
  PencilLine,
  PencilOff,
  PencilRuler,
  Pentagon,
  Percent,
  PersonStanding,
  PhilippinePeso,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  Piano,
  Pickaxe,
  PictureInPicture,
  PictureInPicture2,
  PiggyBank,
  Pilcrow,
  PilcrowLeft,
  PilcrowRight,
  Pill,
  PillBottle,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  Plug,
  Plug2,
  PlugZap,
  Plus,
  Pocket,
  PocketKnife,
  Podcast,
  Pointer,
  PointerOff,
  Popcorn,
  Popsicle,
  PoundSterling,
  Power,
  PowerOff,
  Presentation,
  Printer,
  PrinterCheck,
  Projector,
  Proportions,
  Puzzle,
  Pyramid,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radical,
  Radio,
  RadioReceiver,
  RadioTower,
  Radius,
  RailSymbol,
  Rainbow,
  Rat,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptEuro,
  ReceiptIndianRupee,
  ReceiptJapaneseYen,
  ReceiptPoundSterling,
  ReceiptRussianRuble,
  ReceiptSwissFranc,
  ReceiptText,
  RectangleCircle,
  RectangleEllipsis,
  RectangleGoggles,
  RectangleHorizontal,
  RectangleVertical,
  Recycle,
  Redo,
  Redo2,
  RedoDot,
  RefreshCcw,
  RefreshCcwDot,
  RefreshCw,
  RefreshCwOff,
  Refrigerator,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat1,
  Repeat2,
  Replace,
  ReplaceAll,
  Reply,
  ReplyAll,
  Rewind,
  Ribbon,
  Rocket,
  RockingChair,
  RollerCoaster,
  Rotate3d,
  RotateCcw,
  RotateCcwKey,
  RotateCcwSquare,
  RotateCw,
  RotateCwSquare,
  Route,
  RouteOff,
  Router,
  Rows2,
  Rows3,
  Rows4,
  Rss,
  Ruler,
  RulerDimensionLine,
  RussianRuble,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  SaudiRiyal,
  Save,
  SaveAll,
  SaveOff,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanBarcode,
  ScanEye,
  ScanFace,
  ScanHeart,
  ScanLine,
  ScanQrCode,
  ScanSearch,
  ScanText,
  School,
  Scissors,
  ScissorsLineDashed,
  ScreenShare,
  ScreenShareOff,
  Scroll,
  ScrollText,
  Search,
  SearchCheck,
  SearchCode,
  SearchSlash,
  SearchX,
  Section,
  Send,
  SendHorizontal,
  SendToBack,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Settings2,
  Shapes,
  Share,
  Share2,
  Sheet,
  Shell,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldEllipsis,
  ShieldHalf,
  ShieldMinus,
  ShieldOff,
  ShieldPlus,
  ShieldQuestionMark,
  ShieldUser,
  ShieldX,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shredder,
  Shrimp,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Signature,
  Signpost,
  SignpostBig,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slack,
  Slash,
  Slice,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  Soup,
  Space,
  Spade,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  SpellCheck2,
  Spline,
  SplinePointer,
  Split,
  Spool,
  SprayCan,
  Sprout,
  Square,
  SquareActivity,
  SquareArrowDown,
  SquareArrowDownLeft,
  SquareArrowDownRight,
  SquareArrowLeft,
  SquareArrowOutDownLeft,
  SquareArrowOutDownRight,
  SquareArrowOutUpLeft,
  SquareArrowOutUpRight,
  SquareArrowRight,
  SquareArrowUp,
  SquareArrowUpLeft,
  SquareArrowUpRight,
  SquareAsterisk,
  SquareBottomDashedScissors,
  SquareChartGantt,
  SquareCheck,
  SquareCheckBig,
  SquareChevronDown,
  SquareChevronLeft,
  SquareChevronRight,
  SquareChevronUp,
  SquareCode,
  SquareDashed,
  SquareDashedBottom,
  SquareDashedBottomCode,
  SquareDashedKanban,
  SquareDashedMousePointer,
  SquareDashedTopSolid,
  SquareDivide,
  SquareDot,
  SquareEqual,
  SquareFunction,
  SquareKanban,
  SquareLibrary,
  SquareM,
  SquareMenu,
  SquareMinus,
  SquareMousePointer,
  SquareParking,
  SquareParkingOff,
  SquarePen,
  SquarePercent,
  SquarePi,
  SquarePilcrow,
  SquarePlay,
  SquarePlus,
  SquarePower,
  SquareRadical,
  SquareRoundCorner,
  SquareScissors,
  SquareSigma,
  SquareSlash,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareSquare,
  SquareStack,
  SquareTerminal,
  SquareUser,
  SquareUserRound,
  SquareX,
  SquaresExclude,
  SquaresIntersect,
  SquaresSubtract,
  SquaresUnite,
  Squircle,
  SquircleDashed,
  Squirrel,
  Stamp,
  Star,
  StarHalf,
  StarOff,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SunSnow,
  Sunrise,
  Sunset,
  Superscript,
  SwatchBook,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  TableCellsMerge,
  TableCellsSplit,
  TableColumnsSplit,
  TableOfContents,
  TableProperties,
  TableRowsSplit,
  Tablet,
  TabletSmartphone,
  Tablets,
  Tag,
  Tags,
  Tally1,
  Tally2,
  Tally3,
  Tally4,
  Tally5,
  Tangent,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  TestTube,
  TestTubeDiagonal,
  TestTubes,
  Text,
  TextCursor,
  TextCursorInput,
  TextQuote,
  TextSearch,
  TextSelect,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketPlus,
  TicketSlash,
  TicketX,
  Tickets,
  TicketsPlane,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToolCase,
  Tornado,
  Torus,
  Touchpad,
  TouchpadOff,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  TrainFront,
  TrainFrontTunnel,
  TrainTrack,
  TramFront,
  Transgender,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Trello,
  TrendingDown,
  TrendingUp,
  TrendingUpDown,
  Triangle,
  TriangleAlert,
  TriangleDashed,
  TriangleRight,
  Trophy,
  Truck,
  TruckElectric,
  Turtle,
  Tv,
  TvMinimal,
  TvMinimalPlay,
  Twitch,
  Twitter,
  Type,
  TypeOutline,
  Umbrella,
  UmbrellaOff,
  Underline,
  Undo,
  Undo2,
  UndoDot,
  UnfoldHorizontal,
  UnfoldVertical,
  Ungroup,
  University,
  Unlink,
  Unlink2,
  Unplug,
  Upload,
  Usb,
  User,
  UserCheck,
  UserCog,
  UserLock,
  UserMinus,
  UserPen,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundMinus,
  UserRoundPen,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserX,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  UtilityPole,
  Variable,
  Vault,
  VectorSquare,
  Vegan,
  VenetianMask,
  Venus,
  VenusAndMars,
  Vibrate,
  VibrateOff,
  Video,
  VideoOff,
  Videotape,
  View,
  Voicemail,
  Volleyball,
  Volume,
  Volume1,
  Volume2,
  VolumeOff,
  VolumeX,
  Vote,
  Wallet,
  WalletCards,
  WalletMinimal,
  Wallpaper,
  Wand,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  WavesLadder,
  Waypoints,
  Webcam,
  Webhook,
  WebhookOff,
  Weight,
  Wheat,
  WheatOff,
  WholeWord,
  Wifi,
  WifiCog,
  WifiHigh,
  WifiLow,
  WifiOff,
  WifiPen,
  WifiZero,
  Wind,
  WindArrowDown,
  Wine,
  WineOff,
  Workflow,
  Worm,
  WrapText,
  Wrench,
  X,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

// AI 서비스 기능들과 아이콘, 설명 매핑
export const featureData: Record<
  string,
  { icon: LucideIcon; description: string }
> = {
  // 핵심 대화 및 텍스트 기능
  '생성 기능능': {
    icon: Zap,
    description: '텍스트 설명을 통해 이미지를 생성합니다.',
  },
  '텍스트-비디오 생성': {
    icon: Zap,
    description: '텍스트 설명을 통해 비디오를 생성합니다.',
  },
  '이미지-비디오 생성': {
    icon: Zap,
    description: '이미지를 기반으로 비디오를 생성합니다.',
  },
  '텍스트-음악 생성': {
    icon: Zap,
    description: '텍스트 설명을 통해 음악을 생성합니다.',
  },
  '텍스트-음성 변환': {
    icon: Zap,
    description: '텍스트를 자연스러운 음성으로 변환합니다.',
  },
  'AI 음성 생성': {
    icon: Zap,
    description: 'AI 기술을 활용하여 음성을 생성합니다.',
  },
  'AI 음성 합성': {
    icon: Zap,
    description: 'AI 기술로 자연스러운 음성을 합성합니다.',
  },
  'AI 콘텐츠 생성': {
    icon: Zap,
    description: 'AI를 활용하여 다양한 콘텐츠를 생성합니다.',
  },
  'AI 비디오 생성': {
    icon: Zap,
    description: 'AI 기술로 비디오를 생성합니다.',
  },
  'AI 비디오 편집': {
    icon: Zap,
    description: 'AI 기술을 활용하여 비디오를 편집합니다.',
  },
  'AI 이미지 생성': {
    icon: Zap,
    description: 'AI 기술로 이미지를 생성합니다.',
  },
  'AI 스토리 생성': {
    icon: Zap,
    description: 'AI를 활용하여 스토리를 생성합니다.',
  },
  'AI 스크립트 생성': {
    icon: Zap,
    description: 'AI가 스크립트를 자동으로 생성합니다.',
  },
  'AI 가사 생성': {
    icon: Zap,
    description: 'AI를 활용하여 음악 가사를 생성합니다.',
  },
  'AI 아바타 생성': {
    icon: Zap,
    description: 'AI 기술로 아바타를 생성합니다.',
  },
  'AI 디자인 생성': {
    icon: Zap,
    description: 'AI를 활용하여 디자인을 생성합니다.',
  },
  'AI 웹사이트 생성': {
    icon: Zap,
    description: 'AI 기술로 웹사이트를 생성합니다.',
  },
  'AI 프레젠테이션 생성': {
    icon: Zap,
    description: 'AI를 활용하여 프레젠테이션을 생성합니다.',
  },
  'AI 앱 개발': {
    icon: Zap,
    description: 'AI를 활용하여 앱을 개발합니다.',
  },
  'AI 회의록 생성': {
    icon: Zap,
    description: 'AI가 회의 내용을 분석하여 회의록을 생성합니다.',
  },
  '생성형 채우기': {
    icon: Zap,
    description: '이미지의 빈 공간을 AI가 자동으로 채웁니다.',
  },
  '보컬 생성': {
    icon: Zap,
    description: 'AI가 보컬을 생성합니다.',
  },
  '음악 생성': {
    icon: Zap,
    description: 'AI를 활용하여 음악을 생성합니다.',
  },
  '대화 생성': {
    icon: Zap,
    description: 'AI가 대화를 생성합니다.',
  },
  '차트 생성': {
    icon: Zap,
    description: 'AI를 활용하여 차트를 생성합니다.',
  },
  '콘텐츠 생성': {
    icon: Zap,
    description: 'AI가 다양한 콘텐츠를 생성합니다.',
  },

  // 코딩 기능
  'AI 코드 완성': {
    icon: Zap,
    description: 'AI가 코드를 자동으로 완성합니다.',
  },
  'AI 코드 생성': {
    icon: Zap,
    description: 'AI를 활용하여 코드를 생성합니다.',
  },
  'AI 프롬프트 코딩': {
    icon: Zap,
    description: '자연어 프롬프트를 통해 코딩을 수행합니다.',
  },
  '코드 실행': {
    icon: Zap,
    description: '코드를 실행하고 결과를 확인할 수 있습니다.',
  },
  '코드 리팩토링': {
    icon: Zap,
    description: '기존 코드를 개선하고 최적화합니다.',
  },
  '코드 검색': {
    icon: Zap,
    description: '코드베이스에서 특정 코드를 검색합니다.',
  },
  '코드 리뷰': {
    icon: Zap,
    description: '코드를 검토하고 피드백을 제공합니다.',
  },
  '코드 설명': {
    icon: Zap,
    description: '코드의 기능과 작동 방식을 설명합니다.',
  },
  '자연어 코딩': {
    icon: Zap,
    description: '자연어로 코딩 명령을 내릴 수 있습니다.',
  },
  '프롬프트 기반 개발': {
    icon: Zap,
    description: '프롬프트를 통해 개발을 수행합니다.',
  },
  '테스트 생성': {
    icon: Zap,
    description: '코드에 대한 테스트를 자동으로 생성합니다.',
  },
  '자동 문서화': {
    icon: Zap,
    description: '코드에 대한 문서를 자동으로 생성합니다.',
  },
  '커스텀 모델 훈련': {
    icon: Zap,
    description: '사용자 정의 모델을 훈련시킵니다.',
  },
  '배경 에이전트': {
    icon: Zap,
    description: '백그라운드에서 작업을 수행하는 에이전트입니다.',
  },
  '에이전트 모드': {
    icon: Zap,
    description: '자율적으로 작업을 수행하는 에이전트 모드입니다.',
  },
  '코딩 에이전트': {
    icon: Zap,
    description: '코딩 작업을 자동으로 수행하는 에이전트입니다.',
  },

  // 편집 기능
  '텍스트 기반 편집': {
    icon: Zap,
    description: '텍스트를 기반으로 편집 작업을 수행합니다.',
  },
  '실시간 편집': {
    icon: Zap,
    description: '실시간으로 편집 작업을 수행합니다.',
  },
  '배경 제거': {
    icon: Zap,
    description: '이미지나 비디오에서 배경을 제거합니다.',
  },
  '이미지 편집': {
    icon: Zap,
    description: '이미지를 편집하고 수정합니다.',
  },
  '음성 편집': {
    icon: Zap,
    description: '음성을 편집하고 수정합니다.',
  },
  '벡터 편집': {
    icon: Zap,
    description: '벡터 그래픽을 편집합니다.',
  },
  '캔버스 편집': {
    icon: Zap,
    description: '캔버스에서 편집 작업을 수행합니다.',
  },
  '멀티트랙 편집': {
    icon: Zap,
    description: '여러 트랙을 동시에 편집합니다.',
  },
  '동영상 편집기': {
    icon: Zap,
    description: '동영상을 편집할 수 있는 도구입니다.',
  },
  '매직 박스 편집': {
    icon: Zap,
    description: '매직 박스 기능을 통해 편집을 수행합니다.',
  },
  '시각적 편집기': {
    icon: Zap,
    description: '시각적 인터페이스를 통해 편집을 수행합니다.',
  },
  '이미지 변형': {
    icon: Zap,
    description: '이미지를 변형하고 수정합니다.',
  },
  '이미지 개선': {
    icon: Zap,
    description: '이미지의 품질을 개선합니다.',
  },
  '이미지 업스케일링': {
    icon: Zap,
    description: '이미지의 해상도를 향상시킵니다.',
  },
  '4K 업스케일링': {
    icon: Zap,
    description: '4K 해상도로 업스케일링합니다.',
  },
  '컬러 그레이딩': {
    icon: Zap,
    description: '영상의 색상을 조정합니다.',
  },
  '키프레임 애니메이션': {
    icon: Zap,
    description: '키프레임을 사용하여 애니메이션을 만듭니다.',
  },
  '애니메이션 제작': {
    icon: Zap,
    description: '애니메이션을 제작합니다.',
  },
  '필러 워드 제거': {
    icon: Zap,
    description: '음성에서 불필요한 필러 워드를 제거합니다.',
  },

  // 음성 기능
  '음성 인식': {
    icon: Zap,
    description: '음성을 인식하고 텍스트로 변환합니다.',
  },
  '음성 채팅': {
    icon: Zap,
    description: '음성으로 대화할 수 있습니다.',
  },
  '음성 복제': {
    icon: Zap,
    description: '기존 음성을 복제합니다.',
  },
  '음성 생성': {
    icon: Zap,
    description: 'AI가 음성을 생성합니다.',
  },
  '음성 검색': {
    icon: Zap,
    description: '음성을 통해 검색을 수행합니다.',
  },
  '음성 변환': {
    icon: Zap,
    description: '음성을 다른 형태로 변환합니다.',
  },
  '음성 설계': {
    icon: Zap,
    description: '원하는 음성을 설계합니다.',
  },
  '실시간 전사': {
    icon: Zap,
    description: '실시간으로 음성을 텍스트로 변환합니다.',
  },
  '자동 자막': {
    icon: Zap,
    description: '자동으로 자막을 생성합니다.',
  },
  '화자 분리': {
    icon: Zap,
    description: '여러 화자의 음성을 분리합니다.',
  },
  '더빙 기능': {
    icon: Zap,
    description: '음성 더빙을 수행합니다.',
  },
  'AI 더빙': {
    icon: Zap,
    description: 'AI를 활용하여 더빙을 수행합니다.',
  },
  '감정 표현': {
    icon: Zap,
    description: '음성에 다양한 감정을 표현합니다.',
  },
  '속도 조절': {
    icon: Zap,
    description: '음성의 속도를 조절합니다.',
  },
  '높낮이 조절': {
    icon: Zap,
    description: '음성의 높낮이를 조절합니다.',
  },
  '효과음 지원': {
    icon: Zap,
    description: '다양한 효과음을 지원합니다.',
  },
  '배경음악 추가': {
    icon: Zap,
    description: '배경음악을 추가합니다.',
  },
  '음성 맞춤화': {
    icon: Zap,
    description: '음성을 사용자에게 맞춤화합니다.',
  },
  '음성 스타일': {
    icon: Zap,
    description: '다양한 음성 스타일을 제공합니다.',
  },
  보이스메이커: {
    icon: Zap,
    description: '사용자가 직접 보이스를 만들 수 있습니다.',
  },
  '커스텀 보이스': {
    icon: Zap,
    description: '사용자 정의 보이스를 생성합니다.',
  },
  'OCR 기능': {
    icon: Zap,
    description: '이미지에서 텍스트를 추출합니다.',
  },
  '오프라인 청취': {
    icon: Zap,
    description: '오프라인에서도 음성을 청취할 수 있습니다.',
  },
  '텍스트 하이라이팅': {
    icon: Zap,
    description: '읽고 있는 텍스트를 하이라이팅합니다.',
  },

  // 검색 & 분석 기능
  '실시간 웹 검색': {
    icon: Zap,
    description: '실시간으로 웹에서 정보를 검색합니다.',
  },
  '자연어 검색': {
    icon: Zap,
    description: '자연어로 검색을 수행합니다.',
  },
  '이미지 검색': {
    icon: Zap,
    description: '이미지를 검색합니다.',
  },
  '기업용 검색': {
    icon: Zap,
    description: '기업용 검색 기능을 제공합니다.',
  },
  'AI 검색 엔진': {
    icon: Zap,
    description: 'AI 기반의 검색 엔진입니다.',
  },
  '실시간 정보': {
    icon: Zap,
    description: '실시간 정보를 제공합니다.',
  },
  'Deep Research': {
    icon: Zap,
    description: '심층적인 연구를 수행합니다.',
  },
  '인용 기능': {
    icon: Zap,
    description: '정보의 출처를 인용합니다.',
  },
  '데이터 분석': {
    icon: Zap,
    description: '데이터를 분석합니다.',
  },
  '데이터 시각화': {
    icon: Zap,
    description: '데이터를 시각적으로 표현합니다.',
  },
  '데이터베이스 분석': {
    icon: Zap,
    description: '데이터베이스를 분석합니다.',
  },
  '예측 모델링': {
    icon: Zap,
    description: '예측 모델을 생성합니다.',
  },
  '분석 기능': {
    icon: Zap,
    description: '다양한 분석 기능을 제공합니다.',
  },
  '검색 기능': {
    icon: Zap,
    description: '검색 기능을 제공합니다.',
  },

  // AI 모델 & 처리
  '멀티모달 AI': {
    icon: Zap,
    description: '텍스트, 이미지, 음성 등을 통합적으로 처리합니다.',
  },
  '추론 모델': {
    icon: Zap,
    description: '논리적 추론을 수행하는 모델입니다.',
  },
  '오픈소스 LLM': {
    icon: Zap,
    description: '오픈소스 대규모 언어 모델입니다.',
  },
  '생성형 AI': {
    icon: Zap,
    description: '새로운 콘텐츠를 생성하는 AI입니다.',
  },
  '대화형 AI': {
    icon: Zap,
    description: '대화를 통해 상호작용하는 AI입니다.',
  },
  'AI 어시스턴트': {
    icon: Zap,
    description: '사용자를 도와주는 AI 어시스턴트입니다.',
  },
  'AI 에이전트': {
    icon: Zap,
    description: '자율적으로 작업을 수행하는 AI 에이전트입니다.',
  },
  'AI 서포터': {
    icon: Zap,
    description: '사용자를 지원하는 AI 서포터입니다.',
  },
  'AI 컴패니언': {
    icon: Zap,
    description: '사용자의 동반자 역할을 하는 AI입니다.',
  },
  'AI 캐릭터': {
    icon: Zap,
    description: 'AI로 구현된 캐릭터입니다.',
  },
  'AI 캐릭터 대화': {
    icon: Zap,
    description: 'AI 캐릭터와 대화할 수 있습니다.',
  },
  '멀티네이티브 AI': {
    icon: Zap,
    description: '다국어를 지원하는 AI입니다.',
  },
  '자연어 처리': {
    icon: Zap,
    description: '자연어를 처리하고 이해합니다.',
  },
  '수학 추론': {
    icon: Zap,
    description: '수학적 추론을 수행합니다.',
  },
  '비전 기능': {
    icon: Zap,
    description: '시각적 정보를 처리합니다.',
  },
  '연장된 사고': {
    icon: Zap,
    description: '복잡한 문제를 단계별로 해결합니다.',
  },
  '시스템 프롬프트': {
    icon: Zap,
    description: '시스템 수준의 프롬프트를 지원합니다.',
  },
  'JSON 출력': {
    icon: Zap,
    description: 'JSON 형태로 출력을 제공합니다.',
  },
  '함수 호출': {
    icon: Zap,
    description: '함수를 호출하여 작업을 수행합니다.',
  },
  '모델 증류': {
    icon: Zap,
    description: '큰 모델의 지식을 작은 모델로 전달합니다.',
  },
  '저비용 훈련': {
    icon: Zap,
    description: '저비용으로 모델을 훈련시킵니다.',
  },

  // 특화 기능
  Pikaframes: {
    icon: Zap,
    description: 'Pika Labs의 키프레임 기능입니다.',
  },
  Pikaswaps: {
    icon: Zap,
    description: 'Pika Labs의 객체 교체 기능입니다.',
  },
  Pikadditions: {
    icon: Zap,
    description: 'Pika Labs의 요소 추가 기능입니다.',
  },
  Pikaffects: {
    icon: Zap,
    description: 'Pika Labs의 특수 효과 기능입니다.',
  },
  Pikatwists: {
    icon: Zap,
    description: 'Pika Labs의 트위스트 기능입니다.',
  },
  'Act-One': {
    icon: Zap,
    description: 'Runway의 연기 기능입니다.',
  },
  'Remix 기능': {
    icon: Zap,
    description: '콘텐츠를 리믹스하는 기능입니다.',
  },
  'Re-cut 기능': {
    icon: Zap,
    description: '콘텐츠를 다시 편집하는 기능입니다.',
  },
  'Blend 기능': {
    icon: Zap,
    description: '콘텐츠를 블렌딩하는 기능입니다.',
  },
  'Loop 기능': {
    icon: Zap,
    description: '콘텐츠를 반복하는 기능입니다.',
  },
  'Storyboard 기능': {
    icon: Zap,
    description: '스토리보드를 생성하는 기능입니다.',
  },
  '캔버스 기능': {
    icon: Zap,
    description: '캔버스에서 작업할 수 있는 기능입니다.',
  },
  'Draft 모드': {
    icon: Zap,
    description: '초안을 작성하는 모드입니다.',
  },
  '마법 프롬프트': {
    icon: Zap,
    description: '마법 같은 프롬프트 기능입니다.',
  },
  '프롬프트 향상': {
    icon: Zap,
    description: '프롬프트를 향상시킵니다.',
  },
  '프롬프트 재작성': {
    icon: Zap,
    description: '프롬프트를 재작성합니다.',
  },
  '프롬프트 허브': {
    icon: Zap,
    description: '프롬프트를 공유하는 허브입니다.',
  },
  'ReMi 가사 모델': {
    icon: Zap,
    description: 'Suno의 가사 생성 모델입니다.',
  },
  'Remaster 기능': {
    icon: Zap,
    description: '콘텐츠를 리마스터하는 기능입니다.',
  },
  '커버 기능': {
    icon: Zap,
    description: '음악 커버를 생성하는 기능입니다.',
  },
  'Stem 분리': {
    icon: Zap,
    description: '음악의 악기별 트랙을 분리합니다.',
  },
  '음악 확장': {
    icon: Zap,
    description: '음악을 확장하는 기능입니다.',
  },
  'OtterPilot 봇': {
    icon: Zap,
    description: 'Otter.ai의 전용 봇입니다.',
  },

  // 디자인 & 스타일
  'UI 프로토타입 제작': {
    icon: Zap,
    description: 'UI 프로토타입을 제작합니다.',
  },
  '와이어프레임 제작': {
    icon: Zap,
    description: '와이어프레임을 제작합니다.',
  },
  '반응형 디자인': {
    icon: Zap,
    description: '반응형 디자인을 지원합니다.',
  },
  '벡터 재색칠': {
    icon: Zap,
    description: '벡터 그래픽을 재색칠합니다.',
  },
  '텍스트 효과': {
    icon: Zap,
    description: '텍스트에 다양한 효과를 적용합니다.',
  },
  '텍스트 렌더링': {
    icon: Zap,
    description: '텍스트를 렌더링합니다.',
  },
  '스타일 옵션': {
    icon: Zap,
    description: '다양한 스타일 옵션을 제공합니다.',
  },
  '스타일 코드': {
    icon: Zap,
    description: '스타일 코드를 지원합니다.',
  },
  '다양한 스타일': {
    icon: Zap,
    description: '다양한 스타일을 제공합니다.',
  },
  '애니메이션 스타일': {
    icon: Zap,
    description: '애니메이션 스타일을 지원합니다.',
  },
  포토리얼리즘: {
    icon: Zap,
    description: '사진처럼 사실적인 이미지를 생성합니다.',
  },
  '고화질 생성': {
    icon: Zap,
    description: '고화질 콘텐츠를 생성합니다.',
  },
  '고해상도 변환': {
    icon: Zap,
    description: '고해상도로 변환합니다.',
  },
  '다양한 해상도': {
    icon: Zap,
    description: '다양한 해상도를 지원합니다.',
  },
  '다양한 종횡비': {
    icon: Zap,
    description: '다양한 종횡비를 지원합니다.',
  },
  '4K 60fps 해상도': {
    icon: Zap,
    description: '4K 60fps 해상도를 지원합니다.',
  },
  '10초 1080p 생성': {
    icon: Zap,
    description: '10초 1080p 영상을 생성합니다.',
  },
  '20초 1080p 생성': {
    icon: Zap,
    description: '20초 1080p 영상을 생성합니다.',
  },
  '4분 완곡 생성': {
    icon: Zap,
    description: '4분 완곡을 생성합니다.',
  },
  '배치 생성': {
    icon: Zap,
    description: '여러 개를 한 번에 생성합니다.',
  },
  '실시간 생성': {
    icon: Zap,
    description: '실시간으로 생성합니다.',
  },
  '실시간 처리': {
    icon: Zap,
    description: '실시간으로 처리합니다.',
  },
  '3D 텍스처 생성': {
    icon: Zap,
    description: '3D 텍스처를 생성합니다.',
  },
  '물리 시뮬레이션': {
    icon: Zap,
    description: '물리적 현상을 시뮬레이션합니다.',
  },
  '일관성 유지': {
    icon: Zap,
    description: '콘텐츠의 일관성을 유지합니다.',
  },
  '컬러 팔레트': {
    icon: Zap,
    description: '컬러 팔레트를 제공합니다.',
  },
  '자동 레이아웃': {
    icon: Zap,
    description: '자동으로 레이아웃을 생성합니다.',
  },

  // 언어 & 지역화
  '다국어 지원': {
    icon: Zap,
    description: '다양한 언어를 지원합니다.',
  },
  '25+ 언어 지원': {
    icon: Zap,
    description: '25개 이상의 언어를 지원합니다.',
  },
  '60+ 언어 지원': {
    icon: Zap,
    description: '60개 이상의 언어를 지원합니다.',
  },
  '70+ 언어 지원': {
    icon: Zap,
    description: '70개 이상의 언어를 지원합니다.',
  },
  '100+ 언어 지원': {
    icon: Zap,
    description: '100개 이상의 언어를 지원합니다.',
  },
  '140+ 언어 지원': {
    icon: Zap,
    description: '140개 이상의 언어를 지원합니다.',
  },
  '600+ 언어 지원': {
    icon: Zap,
    description: '600개 이상의 언어를 지원합니다.',
  },
  '20+ 언어 지원': {
    icon: Zap,
    description: '20개 이상의 언어를 지원합니다.',
  },
  '30+ 감정 표현': {
    icon: Zap,
    description: '30개 이상의 감정을 표현합니다.',
  },
  '언어 번역': {
    icon: Zap,
    description: '언어를 번역합니다.',
  },
  '원클릭 번역': {
    icon: Zap,
    description: '한 번의 클릭으로 번역합니다.',
  },
  '자동 번역': {
    icon: Zap,
    description: '자동으로 번역합니다.',
  },
  '톤 조절': {
    icon: Zap,
    description: '텍스트의 톤을 조절합니다.',
  },

  // 통합 & 연동
  'Adobe 앱 통합': {
    icon: Zap,
    description: 'Adobe 앱과 통합하여 사용할 수 있습니다.',
  },
  'ChatGPT 통합': {
    icon: Zap,
    description: 'ChatGPT와 통합하여 사용할 수 있습니다.',
  },
  'Google 앱 통합': {
    icon: Zap,
    description: 'Google 앱과 통합하여 사용할 수 있습니다.',
  },
  'Office 365 통합': {
    icon: Zap,
    description: 'Office 365와 통합하여 사용할 수 있습니다.',
  },
  'Google 워크스페이스 연동': {
    icon: Zap,
    description: 'Google 워크스페이스와 연동하여 사용할 수 있습니다.',
  },
  'X 플랫폼 통합': {
    icon: Zap,
    description: 'X 플랫폼과 통합하여 사용할 수 있습니다.',
  },
  'TikTok 직접 게시': {
    icon: Zap,
    description: 'TikTok에 직접 게시할 수 있습니다.',
  },
  'Discord 통합': {
    icon: Zap,
    description: 'Discord와 통합하여 사용할 수 있습니다.',
  },
  'GitHub 통합': {
    icon: Zap,
    description: 'GitHub와 통합하여 사용할 수 있습니다.',
  },
  'GitHub 연동': {
    icon: Zap,
    description: 'GitHub와 연동하여 사용할 수 있습니다.',
  },
  'Supabase 통합': {
    icon: Zap,
    description: 'Supabase와 통합하여 사용할 수 있습니다.',
  },
  'React/Tailwind 지원': {
    icon: Zap,
    description: 'React와 Tailwind를 지원합니다.',
  },
  'CMS 통합': {
    icon: Zap,
    description: 'CMS와 통합하여 사용할 수 있습니다.',
  },
  '소셜 미디어 연동': {
    icon: Zap,
    description: '소셜 미디어와 연동하여 사용할 수 있습니다.',
  },
  '워드프레스 통합': {
    icon: Zap,
    description: '워드프레스와 통합하여 사용할 수 있습니다.',
  },
  'Canva 통합': {
    icon: Zap,
    description: 'Canva와 통합하여 사용할 수 있습니다.',
  },
  '네이버웍스 연동': {
    icon: Zap,
    description: '네이버웍스와 연동하여 사용할 수 있습니다.',
  },
  '크랙 연동': {
    icon: Zap,
    description: '크랙과 연동하여 사용할 수 있습니다.',
  },
  '카카오톡 챗봇': {
    icon: Zap,
    description: '카카오톡 챗봇으로 사용할 수 있습니다.',
  },
  '앱 연동': {
    icon: Zap,
    description: '다양한 앱과 연동하여 사용할 수 있습니다.',
  },
  '플랫폼 통합': {
    icon: Zap,
    description: '다양한 플랫폼과 통합하여 사용할 수 있습니다.',
  },
  'IDE 통합': {
    icon: Zap,
    description: 'IDE와 통합하여 사용할 수 있습니다.',
  },
  'VS Code 확장': {
    icon: Zap,
    description: 'VS Code 확장으로 사용할 수 있습니다.',
  },
  '다중 IDE 지원': {
    icon: Zap,
    description: '여러 IDE를 지원합니다.',
  },
  'Python/R 지원': {
    icon: Zap,
    description: 'Python과 R을 지원합니다.',
  },
  'Chrome 확장': {
    icon: Zap,
    description: 'Chrome 확장으로 사용할 수 있습니다.',
  },
  '브라우저 확장': {
    icon: Zap,
    description: '브라우저 확장으로 사용할 수 있습니다.',
  },

  // 플랫폼 & 접근성
  '모바일 앱': {
    icon: Zap,
    description: '모바일 앱으로 사용할 수 있습니다.',
  },
  '웹 인터페이스': {
    icon: Zap,
    description:
      '설치 없이 모든 브라우저에서 즉시 접근 가능한 반응형 웹 애플리케이션을 제공합니다.',
  },
  '브라우저 기반 IDE': {
    icon: Zap,
    description:
      '웹 기반 통합 개발 환경으로 코딩, 디버깅, 배포를 한 곳에서 처리합니다.',
  },
  '클라우드 IDE': {
    icon: Zap,
    description:
      '클라우드 컴퓨팅 파워를 활용한 개발 환경으로 협업과 버전 관리를 지원합니다.',
  },
  '로컬 실행': {
    icon: Zap,
    description:
      '인터넷 연결 없이 로컬 컴퓨터에서 완전히 동작하여 데이터 프라이버시를 보장합니다.',
  },
  '온프레미스 배포': {
    icon: Zap,
    description:
      '기업 내부 서버에 직접 설치하여 완전한 데이터 통제권과 보안을 확보할 수 있습니다.',
  },
  '기업용 배포': {
    icon: Zap,
    description:
      '대규모 조직을 위한 확장 가능한 인프라와 관리자 도구, SSO 통합을 제공합니다.',
  },
  '웹 앱 지원': {
    icon: Zap,
    description: 'PWA 기술로 앱 같은 웹 경험을 제공합니다.',
  },
  '50+ 언어 지원': {
    icon: Zap,
    description: '50개 이상의 프로그래밍 언어를 지원합니다.',
  },

  // 협업 & 공유
  '실시간 협업': {
    icon: Zap,
    description: '여러 사용자의 실시간 변경사항을 확인하고 충돌을 방지합니다.',
  },
  '공유 기능': {
    icon: Zap,
    description: '콘텐츠를 공유할 수 있습니다.',
  },
  '그룹 채팅': {
    icon: Zap,
    description: '그룹으로 채팅할 수 있습니다.',
  },
  '협업 기능': {
    icon: Zap,
    description: '협업 기능을 제공합니다.',
  },
  '커뮤니티 기능': {
    icon: Zap,
    description: '사용자 간 지식 공유가 가능한 커뮤니티 플랫폼을 제공합니다.',
  },
  '실시간 미리보기': {
    icon: Zap,
    description:
      '편집 중인 내용을 실시간으로 미리 확인하여 결과물을 즉시 검토하고 수정할 수 있습니다.',
  },
  '파일 업로드': {
    icon: Zap,
    description: '다양한 파일 형식을 업로드할 수 있습니다.',
  },
  '메모 기능': {
    icon: Zap,
    description: '녹음 중 특정 구간에 메모를 남길 수 있습니다.',
  },
  '북마크 기능': {
    icon: Zap,
    description: '녹음 중 특정 구간에 북마크를 설정할 수 있습니다.',
  },
  '미팅 노트': {
    icon: Zap,
    description:
      '회의 중 실시간 음성 인식으로 자동 기록하고 요약, 액션 아이템을 추출합니다.',
  },
  '메모리 기능': {
    icon: Zap,
    description:
      '이전 대화와 작업 맥락을 기억하여 연속성 있는 상호작용과 개인화된 서비스를 제공합니다.',
  },
  '아티팩트 생성': {
    icon: Zap,
    description:
      '코드, 문서, 이미지 등 완성된 결과물을 독립적인 아티팩트로 생성하고 재사용할 수 있습니다.',
  },

  // 캐릭터 & 페르소나
  '커스텀 캐릭터 생성': {
    icon: Zap,
    description: '사용자 정의 캐릭터를 생성할 수 있습니다.',
  },
  '페르소나 기능': {
    icon: Zap,
    description: '다양한 역할의 AI 페르소나 기능을 제공합니다.',
  },
  롤플레이: {
    icon: Zap,
    description:
      '역사적 인물, 소설 캐릭터와의 몰입형 대화로 창의적 학습과 엔터테인먼트를 제공합니다.',
  },
  '애니메이션 아바타': {
    icon: Zap,
    description:
      '자연스러운 3D 애니메이션 아바타로 생동감 있는 상호작용을 경험합니다.',
  },
  '커스텀 아바타': {
    icon: Zap,
    description: '나만의 아바타를 생성하고 자유롭게 커스터마이징합니다.',
  },
  '100+ AI 아바타': {
    icon: Zap,
    description: '100개 이상의 AI 아바타를 제공합니다.',
  },
  '230+ AI 아바타': {
    icon: Zap,
    description: '230개 이상의 AI 아바타를 제공합니다.',
  },
  '1000+ AI 음성': {
    icon: Zap,
    description: '1000개 이상의 AI 음성을 제공합니다.',
  },
  '340+ AI 보이스': {
    icon: Zap,
    description: '340개 이상의 AI 보이스를 제공합니다.',
  },
  '200+ AI 음성': {
    icon: Zap,
    description: '200개 이상의 AI 음성을 제공합니다.',
  },
  '500+ 음성 옵션': {
    icon: Zap,
    description: '500개 이상의 음성 옵션을 제공합니다.',
  },
  '300+ 음성 옵션': {
    icon: Zap,
    description: '300개 이상의 음성 옵션을 제공합니다.',
  },
  '창작 지원': {
    icon: Zap,
    description: '창작 활동을 지원합니다.',
  },
  '나만의 AI': {
    icon: Zap,
    description: `'나만의 AI'라는 이름의 개인화 AI 챗봇 기능을 지원합니다.`,
  },

  // 보안 & 개인정보
  '프라이버시 보호': {
    icon: Zap,
    description: '사용자 개인정보를 보호합니다.',
  },
  '기업용 보안': {
    icon: Zap,
    description: '엔터프라이즈급 보안 체계를 제공합니다.',
  },
  '보안 기능': {
    icon: Zap,
    description: '전방위 보안 시스템을 구축합니다.',
  },
  '보안 및 규정 준수': {
    icon: Zap,
    description: '주요 보안 인증 및 규정 준수를 보장합니다.',
  },
  '안전 필터': {
    icon: Zap,
    description: '유해 콘텐츠를 실시간으로 탐지합니다.',
  },
  '콘텐츠 검증': {
    icon: Zap,
    description: '정확하고 안전한 정보만을 제공합니다.',
  },
  '저작권 보호': {
    icon: Zap,
    description: '저작권 침해를 방지하고 창작자 권리를 보호합니다.',
  },
  'C2PA 메타데이터': {
    icon: Zap,
    description:
      '콘텐츠 출처 증명 표준 C2PA로 디지털 미디어의 진위성과 생성 과정을 투명하게 추적합니다.',
  },
  '워터마크 시스템': {
    icon: Zap,
    description:
      '디지털 워터마크를 삽입하여 출처와 소유권을 명확히 할 수 있는 기능을 제공합니다..',
  },
  '제로 데이터 보존': {
    icon: Zap,
    description: '사용자 입력 데이터를 서버에 보존하지 않습니다.',
  },
  '코드 소유권': {
    icon: Zap,
    description:
      'AI가 생성한 모든 코드의 완전한 소유권을 사용자에게 제공합니다..',
  },
  '무검열 콘텐츠': {
    icon: Zap,
    description: '합법적 범위 내에서 제한 없는 콘텐츠 생성을 지원합니다.',
  },

  // 브랜딩 & 커스터마이징
  '브랜드 보이스': {
    icon: Zap,
    description:
      '브랜드 고유의 톤앤매너, 문체, 가치관을 학습하여 일관된 브랜드 메시지를 생성합니다.',
  },
  '브랜드 키트': {
    icon: Zap,
    description: '브랜드 아이덴티티를 일관되게 유지합니다.',
  },
  '브랜딩 기능': {
    icon: Zap,
    description:
      '모든 생성 콘텐츠에 브랜드 가이드라인을 자동 적용하여 통일된 브랜드 경험을 제공합니다.',
  },
  '브랜드 커스터마이징': {
    icon: Zap,
    description: '브랜드만의 독특한 작업 환경을 구축합니다.',
  },
  '커스텀 모델': {
    icon: Zap,
    description: '사용자 정의 모델을 만들 수 있습니다.',
  },
  '자동 레이어 명명': {
    icon: Zap,
    description:
      '디자인 요소를 분석하여 의미 있고 체계적인 레이어명을 자동 생성하여 파일 관리 효율성을 높입니다.',
  },
  '디자인 시스템': {
    icon: Zap,
    description:
      '컴포넌트, 스타일 가이드, 토큰을 체계화한 디자인 시스템으로 일관된 UI/UX를 구축하고 관리합니다.',
  },

  // 분석 & 최적화
  'SEO 최적화': {
    icon: Zap,
    description:
      '검색엔진 순위 향상을 위한 키워드 분석, 메타태그 최적화, 콘텐츠 구조 개선을 제공합니다.',
  },
  '표절 검사': {
    icon: Zap,
    description:
      '텍스트의 독창성을 검증하고 중복 콘텐츠를 탐지하여 저작권 문제를 방지합니다.',
  },
  'A/B 테스트': {
    icon: Zap,
    description:
      '두 가지 버전의 성과를 비교 분석하여 최적의 마케팅 전략을 도출합니다.',
  },
  '마케팅 자동화': {
    icon: Zap,
    description:
      '이메일 캠페인, 소셜미디어 포스팅, 고객 세분화를 자동으로 관리합니다.',
  },
  '워크플로우 자동화': {
    icon: Zap,
    description:
      '반복적인 업무 프로세스를 자동화하여 효율성을 극대화하고 인적 오류를 줄입니다.',
  },
  '자동 요약': {
    icon: Zap,
    description:
      '긴 문서나 기사의 핵심 내용을 추출하여 간결한 요약문을 생성합니다.',
  },
  '문법 검사': {
    icon: Zap,
    description: '맞춤법, 문법, 문체를 검토하고 개선 제안을 제공합니다.',
  },
  '파라미터 조정': {
    icon: Zap,
    description:
      'AI 모델의 출력 품질을 위한 온도, 최대 토큰, 창의성 수준 등을 세밀하게 조정합니다.',
  },
  '이미지 가이드': {
    icon: Zap,
    description:
      '가이드라인에 맞는 이미지 생성을 위한 스타일 가이드와 템플릿을 제공합니다.',
  },
  '스크립트 변환': {
    icon: Zap,
    description:
      '다양한 프로그래밍 언어 간 코드 변환 및 레거시 시스템 마이그레이션을 지원합니다.',
  },
  'URL 변환': {
    icon: Zap,
    description:
      '홈페이지, 제품 페이지, 블로그 게시물 등 모든 URL에서 쉽게 동영상을 만들 수 있습니다.',
  },
  '비디오 요약': {
    icon: Zap,
    description: '영상 콘텐츠의 음성과 자막을 분석하여 핵심 내용을 추출합니다.',
  },
  'AI 요약': {
    icon: Zap,
    description: '인공지능을 활용한 분석으로 요약을 생성합니다.',
  },

  // 개발 & 배포
  'API 제공': {
    icon: Zap,
    description: 'API를 통해 외부 서비스와의 원활한 데이터 연동을 지원합니다.',
  },
  'Live API': {
    icon: Zap,
    description:
      '실시간 데이터 스트리밍과 웹소켓 연결을 통한 즉시 응답 API를 제공합니다.',
  },
  '원클릭 배포': {
    icon: Zap,
    description: '한 번의 클릭으로 배포할 수 있습니다.',
  },
  '버전 관리': {
    icon: Zap,
    description:
      'Git 기반의 소스코드 버전 관리와 릴리즈 히스토리 추적을 제공합니다.',
  },
  'npm 패키지 관리': {
    icon: Zap,
    description: 'Node.js 패키지의 설치, 업데이트, 의존성 관리를 자동화합니다.',
  },
  '프레임워크 지원': {
    icon: Zap,
    description:
      'React, Vue, Angular, Next.js 등 주요 프론트엔드 프레임워크를 포괄적으로 지원합니다.',
  },
  '풀스택 웹 개발': {
    icon: Zap,
    description:
      '프론트엔드부터 백엔드, 데이터베이스까지 전체 웹 애플리케이션 개발을 지원합니다.',
  },
  '데이터베이스 통합': {
    icon: Zap,
    description: '다양한 데이터베이스와의 연결 및 ORM 설정을 제공합니다.',
  },
  '인증 시스템': {
    icon: Zap,
    description: '보안성 높은 사용자 인증 시스템을 구축합니다.',
  },
  '비전 코딩': {
    icon: Zap,
    description:
      '이미지나 와이어프레임을 분석하여 자동으로 UI 코드를 생성합니다.',
  },
  '상업적 사용': {
    icon: Zap,
    description: '제약 없이 사용할 수 있는 상업적 라이센스를 제공합니다.',
  },
  '무료 체험': {
    icon: Zap,
    description: '기능을 체험할 수 있는 무료 트라이얼을 제공합니다.',
  },
  '에이전트 스토어': {
    icon: Zap,
    description:
      '에이전트들을 탐색하고 설치할 수 있는 마켓플레이스를 제공합니다.',
  },
  '모바일 앱 개발': {
    icon: Zap,
    description: '모바일 앱을 개발할 수 있습니다.',
  },

  // 템플릿 & 리소스
  '템플릿 제공': {
    icon: Zap,
    description: '다양한 템플릿을 제공하여 빠른 프로젝트 시작을 지원합니다.',
  },
  '소셜 미디어 템플릿': {
    icon: Zap,
    description:
      '인스타그램, 페이스북, 트위터 등 플랫폼별 최적화된 게시물 템플릿을 제공합니다.',
  },
  '소셜 미디어 콘텐츠': {
    icon: Zap,
    description: '소셜 미디어 콘텐츠를 생성합니다.',
  },
  '16M+ 스톡 미디어': {
    icon: Zap,
    description:
      '고품질 사진, 일러스트, 벡터 이미지 1,600만 개 이상을 로열티 프리로 제공합니다.',
  },
  '미디어 라이브러리': {
    icon: Zap,
    description:
      '미디어 파일을 체계적으로 관리하고 태그별로 분류하여 쉽게 검색할 수 있습니다.',
  },
  '인터랙티브 요소': {
    icon: Zap,
    description:
      '버튼, 슬라이더, 애니메이션 등 사용자 참여를 높이는 동적 UI 컴포넌트를 제공합니다.',
  },
  '인터랙티브 앱 생성': {
    icon: Zap,
    description: '사용자와 상호작용하는 웹앱을 제작합니다.',
  },
  'PPT 내보내기': {
    icon: Zap,
    description:
      '작성한 콘텐츠를 PowerPoint 형식으로 변환하여 프레젠테이션용으로 활용할 수 있습니다.',
  },
  'PDF 내보내기': {
    icon: Zap,
    description:
      '문서를 고품질 PDF로 변환하여 인쇄 및 배포가 용이하도록 지원합니다.',
  },
  '스크린 레코딩': {
    icon: Zap,
    description: '화면 활동을 녹화하여 영상을 제작할 수 있습니다.',
  },
  '자동 차트 생성': {
    icon: Zap,
    description: '데이터를 분석하여 차트를 생성합니다.',
  },
  'AI 스프레드시트': {
    icon: Zap,
    description:
      '즉각적인 데이터 시각화, 동적 디자인을 포함한 스프레드시트를 제공합니다..',
  },

  // 특수 기능
  '텍스트 어드벤처': {
    icon: Zap,
    description:
      'AI가 생성하는 스토리 기반 텍스트 어드벤처 게임으로 창의적 글쓰기를 학습할 수 있습니다.',
  },
  '로어북 시스템': {
    icon: Zap,
    description:
      '소설이나 게임의 세계관, 캐릭터 설정을 체계적으로 관리하고 일관성을 유지합니다.',
  },
  'AI 모델 선택': {
    icon: Zap,
    description: '용도에 맞는 다양한 AI 모델을 선택하여 사용할 수 있습니다.',
  },
  '다양한 데이터 형식': {
    icon: Zap,
    description: '다양한 데이터 형식을 지원합니다.',
  },
  '수학 문제 해결': {
    icon: Zap,
    description: '복잡한 수식, 미적분, 통계 문제 등을 해결합니다.',
  },
  '도구 기능': {
    icon: Zap,
    description: '다양한 유형의 글을 쓸 수 있도록 도움을 드립니다.',
  },
  '7초 뉴스': {
    icon: Zap,
    description:
      '실시간 뉴스를 7초 내에 핵심만 요약하여 빠른 정보 습득을 지원합니다.',
  },
  뤼튼스피킹: {
    icon: Zap,
    description:
      '실시간 음성 대화를 통해 자연스러운 언어 학습과 발음 교정을 제공합니다.',
  },
  'Figma Make': {
    icon: Zap,
    description:
      'Figma 디자인을 실제 동작하는 웹 컴포넌트로 자동 변환하여 개발 시간을 단축합니다.',
  },
  'Figma Sites': {
    icon: Zap,
    description:
      'Figma 디자인을 그대로 반영한 반응형 웹사이트를 자동으로 생성하고 호스팅합니다.',
  },
  'AI 워크샵': {
    icon: Zap,
    description:
      'AI 활용법부터 고급 기술까지 단계별 학습 과정과 실습 환경을 제공합니다.',
  },
  'SCORM 지원': {
    icon: Zap,
    description:
      'e-러닝 표준 SCORM 패키지 생성으로 LMS와 호환되는 교육 콘텐츠를 제작합니다.',
  },
  인페인팅: {
    icon: Zap,
    description:
      '이미지의 특정 영역을 선택하여 AI가 자연스럽게 다시 그려주는 편집 기능입니다.',
  },
  아웃페인팅: {
    icon: Zap,
    description:
      '기존 이미지의 경계를 확장하여 더 넓은 장면을 자연스럽게 생성합니다.',
  },
  ControlNet: {
    icon: Zap,
    description:
      '포즈, 깊이, 엣지 등을 제어하여 원하는 구도와 스타일의 이미지를 정밀하게 생성합니다.',
  },
  'LoRA 지원': {
    icon: Zap,
    description:
      '특정 스타일이나 캐릭터를 학습한 LoRA 모델을 적용하여 일관된 이미지를 생성합니다.',
  },
  '오픈소스 모델': {
    icon: Zap,
    description:
      '오픈소스 AI 모델을 자유롭게 사용하고 커스터마이징할 수 있습니다.',
  },
  'V7 모델': {
    icon: Zap,
    description:
      '최신 V7 이미지 생성 모델로 더욱 정교하고 현실적인 이미지를 생성합니다.',
  },
  'Gen-4 모델': {
    icon: Zap,
    description:
      '4세대 AI 모델의 향상된 성능으로 더 정확하고 창의적인 결과물을 제공합니다.',
  },
  'Jasper Chat': {
    icon: Zap,
    description:
      '마케팅 전문 AI 어시스턴트로 브랜드 톤앤매너에 맞는 콘텐츠 제작을 지원합니다.',
  },
  Chatsonic: {
    icon: Zap,
    description:
      '실시간 정보 검색과 음성 대화가 가능한 차세대 AI 챗봇 서비스입니다.',
  },
  Photosonic: {
    icon: Zap,
    description:
      '텍스트 설명만으로 고품질 AI 아트워크와 사실적인 이미지를 생성합니다.',
  },
  Botsonic: {
    icon: Zap,
    description:
      '웹사이트용 맞춤형 AI 챗봇을 노코드로 구축하고 고객 서비스를 자동화합니다.',
  },
  'AI 글쓰기 도구': {
    icon: Zap,
    description: '더 나은 글쓰기, 더 효율적인 문서 작성을 도와드립니다..',
  },
  'AI 음성 스튜디오': {
    icon: Zap,
    description:
      '텍스트를 자연스러운 음성으로 변환하고 목소리 톤과 감정을 세밀하게 조정합니다..',
  },
  '실시간 피드백': {
    icon: Zap,
    description:
      '작업 과정에서 즉시 개선 제안과 오류 수정 가이드를 제공합니다.',
  },
  '멀티봇 채팅': {
    icon: Zap,
    description:
      '여러 AI 봇과 동시에 대화하여 다양한 관점의 답변을 비교할 수 있습니다.',
  },
  '커스텀 봇 생성': {
    icon: Zap,
    description:
      '특정 업무나 성격에 맞는 전용 AI 봇을 직접 설계하고 훈련시킬 수 있습니다.',
  },
  '수익화 기능': {
    icon: Zap,
    description:
      '제작한 콘텐츠나 봇을 마켓플레이스에 판매하여 수익을 창출할 수 있습니다.',
  },
  '프리뷰 기능': {
    icon: Zap,
    description:
      '완성 전에 실시간으로 결과물을 미리 확인하고 수정할 수 있는 실시간 미리보기를 제공합니다.',
  },
};

// 기본 아이콘과 설명 (매핑되지 않은 기능에 사용)
export const defaultFeatureData = {
  icon: Sparkles,
  description: '이 기능을 통해 더욱 효율적인 작업이 가능합니다.',
};

// 기능명으로 아이콘과 설명을 가져오는 함수
export function getFeatureData(featureName: string): {
  icon: LucideIcon;
  description: string;
} {
  // 정확히 일치하는 기능명 검색
  if (featureData[featureName]) {
    return featureData[featureName];
  }

  // 기본값으로 폴백

  return defaultFeatureData;
}

// 기능명으로 아이콘만 가져오는 함수 (기존 호환성 유지)
export function getFeatureIcon(featureName: string): LucideIcon {
  return getFeatureData(featureName).icon;
}
